apiVersion: v1
kind: Service
metadata:
  name: goqur-functions-service
spec:
  type: LoadBalancer
  selector:
    app: goqur-functions
  ports: 
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000      