name: Fetch AZ Search values 

on:
  [workflow_dispatch]

jobs:
  fetch:
    name: Fetch search service keys
    runs-on: ubuntu-latest
    steps:
      - name: Login to Azure 
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: Run Azure CLI to retrieve search service keys and send to the output
        id: azure-search-keys
        run: |
          az search admin-key show --service-name gq-search-svc --resource-group gq-search-rg
      
      - name: Run Azure CLI to retrieve search service keys and send to the output
        id: azure-search-keys2
        run: |
          echo "::set-output name=SEARCH_KEYS::$(az search admin-key show --service-name gq-search-svc --resource-group gq-search-rg)"
      
      - name: Display primary key by scraping the previous step output
        run: |
          echo "Primary keys is ${{ steps.azure-search-keys.outputs.primaryKey }}"

      - name: Display primary key by scraping the previous step output
        run: |
          echo "Primary keys is ${{ steps.search.outputs.SEARCH_KEYS }}"
