name: Prepare and Upload CSV to Azure Blob

on:
  [workflow_dispatch]

# on:
#   push:
#     branches: [ main ]

# WARNING: Make sure to have a blob storage container called `files` created in the storage.
env:
  GQ_STORAGE_CONTAINER: files             # goqur storage container name

jobs:
  upload:
    runs-on: windows-latest

    steps:
      - name: Checkout the repo 
        uses: actions/checkout@v2

      # Prepare Ayahs for upload by making sure that the fields have double-quotes around them
      - name: Prepare CSV file
        run: ./prepare-ayahs-4-upload.ps1
      
      - name: Upload to Azure Blob
        uses: LanceMcCarthy/Action-AzureBlobUpload@v1.9.0
        with:
          connection_string: ${{secrets.AZURE_STORAGE_KEY}}
          container_name: ${{ env.GQ_STORAGE_CONTAINER }}
          source_folder: ./uploads 
          # Optional parameters
          fail_if_source_empty: false
          is_recursive: false
