name: Prepare and Upload CSV to Azure Blob

on:
  push:
    branches: [ main ]

jobs:
  upload:
    runs-on: windows-latest

    steps:
      - name: Checkout the repo 
        uses: actions/checkout@v2

      # Prepare Ayahs for upload by making sure that the fields have double-quotes around them
      - name: Prepare CSV file
        run: ./prepare-ayahs-4-upload.ps1
      
      - name: Upload to Azure Blob
        uses: LanceMcCarthy/Action-AzureBlobUpload@v1.9.0
        with:
          connection_string: ${{secrets.AZURE_STORAGE_KEY}}
          container_name: files
          source_folder: ./uploads 
          # Optional parameters
          fail_if_source_empty: false
          is_recursive: false
