name: Prepare and Upload CSV to Azure Blob

on:
  push:
    branches: [ main ]

jobs:
  upload:
    runs-on: windows-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Prepare Ayahs for upload
      - name: Prepare CSV file
        run: ./prepare-ayahs-4-upload.ps1
      
      # Upload Ayahs CSV to blob
      - name: Upload to Azure Blob
        uses: LanceMcCarthy/Action-AzureBlobUpload@v1.9.0
        with:
          # Azure Storage ConnectionString for the container (Azure Portal - select Storage Account - Access Keys blade).
          connection_string: ${{secrets.AZURE_STORAGE_KEY}}
          # Blob Container name (e.g. my-container).
          container_name: files
          # The local folder containing all the files and subfolders to upload to the blob container (use a trailing slash)
          source_folder: ./uploads 
          # Optional parameters
          fail_if_source_empty: false
          is_recursive: false
